#!/usr/bin/env bash

#Check if all four parameters are proovided

if [ "$#" -lt 4 ]; then
	echo  "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

#Display info about tjhe transfer
#echo "Transferring file to server"
#echo "File path: $file_path"
#echo "Server IP: $server IP"
#echo "Username: #usernam"
#echo "SSH Key path: #ssh_key_path"

#Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

#check the exit status of the scp command
if [ $? -eq 0 ]; then
	echo "File transfer successful!"
else 
	echo "Erro transferring file"
fi

