#!/usr/bin/env bash
# Install Nginx and the init file have only a message

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
suod service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

