#!/usr/bin/env bash
# This scripts installs Nginx on a ubuntu server



# update the package list
apt-get update -y

# install nginx
apt-get install nginx -y


# create an html file that nginx will serve
echo "Hello world" > /var/www/html/index.html

# Ensure nginx is on port 80 and restarts using init.d
/etc/init.d/nginx restart


# verify
echo "Nginx has been installed and configured.You can verify with curl."

